### ISSUE TITLE
Problem rendering list of CAIPS required

### ISSUE THREAD

**Issue by ligi** [ChainAgnostic/CAIPs#240]
If the value of "requires" is a list - then the rendering and linking is broken.

![image](https://github.com/ChainAgnostic/chainagnostic/assets/111600/273203b0-b379-4185-ba65-2b574082f12b)

**Comment by bumblefudge** [comment]
Embarassing! It's just the liquid templating in jekyll interacting with non-normalized (and in some cases invalid) YAML.  For example

1. It works on CAIP-25, where [a proper YAML integer array without brackets](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-25.md?plain=1#L10)
renders as
![image](https://github.com/ChainAgnostic/CAIPs/assets/37127325/3538efa3-14eb-48c9-a062-7b7f1abb0c99)
2. In CAIP-211, where [there are brackets but not quotes](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-211.md?plain=1#L10), it works but the square brackets break the links, and
![image](https://github.com/ChainAgnostic/CAIPs/assets/37127325/4eea6d67-b528-4956-bff8-fda58567830b)

3. In CAIP-222, which you screengrabbed above, there are [both brackets and quotes](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-222.md?plain=1#L9).

I thought I already fixed all these glitches in all the CAIPs before paternity leave, but maybe they crept back in through a bad unsquashed merge or these are just new since then.  I'll make a PR that fixes all the frontmatter arrays in the whole repo momentarily.
