### ISSUE TITLE
CAIP-122: address or account_id?

### ISSUE THREAD

**Issue by jdsika** [ChainAgnostic/CAIPs#266]
I was wondering why the term "address" is used in the example message structure and the data model even if it clearly states that the chain ID should be used as a prefix. In this case the name should be "account_id" as of CAIP-10?

In addition the place in the example message where it states **blockchain** should be namespace{account_id} imo?

**Comment by jdsika** [comment]
Another question:
In [CAIP-10](https://chainagnostic.org/CAIPs/caip-10) you use underscores like "account_id" but in the data model of the CAIP-122 you use dashs like "expiration-time". I think there should be a naming convention that says either or?

**Comment by bumblefudge** [comment]
I think CAIP-122 was modeled on EIP-4361, where "address" was used-- it would be more consistent with CAIP-10 (and more chain-agnostic) to call it an account_id tho, since that's what you're authenticating? feel free to open a PR for this.

as for the convention, there isn't one project-wide or org-wide.  maybe there should be? if you open a separate PR on https://github.com/ChainAgnostic/CAIPs/blob/main/CONTRIBUTING.md#style-guide I will shop it around to other contributors and if it gets traction I will update all pre-final CAIPs accordingly.  I don't know that an org-wide convention for property names/syntaxs makes a lot of sense because many of those have to conform to use-case-specific conventions and user/dev expectations, but definitely the "internal stuff" like how we refer to components of a CAIP scheme definitely would benefit from a convention!
